version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    env_file:
      - ./app.env
    ports:
      - "6500:5432"  # External port 6500, container port 5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network


volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
